defaults:
  - nonlinear_geoff

model:
  weight_init_method: zeros # zeros, kaiming_uniform
  n_layers: 1

task:
  name: nonlinear_geoff
  type: regression
  n_real_features: 1
  n_features: 2
  flip_rate: 0.001
  n_layers: 1
  std_normal_distractors_only: true # Distractor spikes experiment only

train:
  optimizer: sgd
  batch_size: 1
  learning_rate: 0.005
  total_steps: 20000
  log_freq: 1
  normalize_loss: false # Distractor spikes experiment only
  force_real_weight_val: null # Distractor spikes experiment only

feature_recycling:
  distractor_chance: 0.0
  recycle_rate: 0.0
  use_cbp_utility: false