seed: 0
half_precision: False
cache_jit: True

train:
  steps: 1_000_000  # In number of environment steps
  tbptt_window: 20
  per_env_batch_size: 16
  log_interval: 10_000 # In number of environment steps

model:
  feature_extractor:
    type: "cnn"
    activation: "gelu"
    embedding_dim: 256
  actor_critic:
    actor_layer_sizes: [256, 256]
    critic_layer_sizes: [256, 256]
    activation: "gelu"

optimizer:
  learning_rate: 3e-4

env:
  # disable_jit: True
  n_envs: 1
  type: "xminigrid" # Valid options: "xminigrid"
  name: "MiniGrid-Empty-6x6"
  wrappers:
    - "DmEnvAutoResetWrapper"
    - "RGBImgObservationWrapper"
    - "XMObsDownscaleWrapper"
    - "XMRGBPreprocessWrapper"

wandb:
  enabled: False
  entity: "ejmejm"
  project: "discovery-test"